### ISSUE TITLE
Skiperator creates empty Sidecar-resources

### ISSUE THREAD

**Issue by esphen** [kartverket/skiperator#23]
The sidecar resource gets the following spec:

```
  spec:
    outboundTrafficPolicy: {}
```

This is potentially a bug in the enum from the library we use. The enum value is 0 and this may be recieved as a null value somewhere and not properly mapped to `REGISTRY_ONLY` in the YAML. It is set in the code: https://github.com/kartverket/skiperator/blob/main/controllers/sidecar.go#L53

**Comment by hagen93** [comment]
REGISTRY_ONLY is the default value and thus removed by the library. Looks weird, but works just fine as default is picked up on the other side too. I tested this while developing the feature.
