### ISSUE TITLE
accessPolicy rules without matching services gives error

### ISSUE THREAD

**Issue by esphen** [kartverket/skiperator#24]
When adding a new accessPolicy rule a lookup is done on a matching service. See https://github.com/kartverket/skiperator/blob/main/controllers/network_policy.go#L209. When this does not exist it fails in creating the NetworkPolicy entirely, thus disabling zero trust for that pod. 

The behavior of this error is not obvious to the product teams as other resources are created correctly and networking is functional. This could instead be "logged" as an event in the namespace and skipped rather than aborting the creation of the NetworkPolicy. 

The intended behavior should be that the NetworkPolicy is created despite of any failures so that the deny-all rules always are correctly applied.

**Comment by hagen93** [comment]
Fixed in 7ac09fe2ffb20c646d4c533a86b460fdc6e3b52c
